updating sticky nav bar for new navigation, removed temp nav from app.js
B-U-I-L-T-UIUC/BUILT-Website pull request #25
Opened 2024-10-12 05:01 UTC by alognz

closes #7 

closed other pr bc i was having rebase issues that couldnt be fixed :D: but heres a gif of what the sticky nav bar looks like

![stickynavbargid](https://github.com/user-attachments/assets/87fe748b-98a9-470c-9465-c7f1dfdf8f37)

2024-10-12 05:41 UTC, boldenj2 commented on src/components/stickyNavBar.js
> +      <style>
For the sake of consistency and organization, can you put this in a `stickyNavBar.css` file

2024-10-12 05:42 UTC, boldenj2 requested changes
Other than the small nit comment, everything else looks good.

2024-10-12 06:04 UTC, alognz commented
i cant make changes bc my push is being declined due to repository rule violations, ill close and make another branch tomorrow

2024-10-14 04:23 UTC, scuruchima1 commented
@alognz @boldenj2 the push might be prevented because of the unresolved conversation. other than that, Alondra you should be able to commit to the branch then commit after you resolve Bolden's comment. If not let me know.

2024-10-14 22:17 UTC, scuruchima1 approved these changes

2024-10-14 22:22 UTC, boldenj2 approved these changes

2024-10-14 22:23 UTC, merged