Add home image carousel component
B-U-I-L-T-UIUC/BUILT-Website pull request #37
Opened 2024-11-05 04:03 UTC by scuruchima1

![Screen Recording 2024-11-04 at 9 28 32 PM-2](https://github.com/user-attachments/assets/c5d95877-f5db-45ef-b449-2c8661473d05)

2024-11-05 04:04 UTC, scuruchima1 commented
the rebasing lowkey messed up but its all good for merging

2024-11-05 07:01 UTC, boldenj2 requested changes
Looks good! I just want you to add a couple things. First, can you make the images in the carousel have the same height and width. Second, you also add some side buttons to scroll back and forth. Lastly, when you make prs can you add some more detail than just a video.

2024-11-10 23:48 UTC, scuruchima1 commented
<img width="1512" alt="Screenshot 2024-11-10 at 5 42 20 PM" src="https://github.com/user-attachments/assets/cfe6ef9a-104b-4f3b-9340-e860216d21fd">

This is the new look with small arrows on the bottom that allow for scrolling through the images. For images to have the same height I'm not sure if cropping images to a certain size is the way to go here, or if we should just get rid of vertical images completely in the carousel. 

I have also changed the component so it can be better reused. The component now takes in a list of image file names instead of having the file names hard coded within the component.

2024-11-11 01:25 UTC, boldenj2 requested changes
Thank you for the changes, just one last thing. I noticed when I tested your code locally, the image carousel is a bit glitchy due to the auto-scroll timer not being reset. 

Example:
https://github.com/user-attachments/assets/d00b8771-f2f5-4916-a4fe-0535c08dca2c

2024-11-11 01:25 UTC, boldenj2 commented on src/components/PhotoCarousal.js
> +    setFade(false); // Trigger fade-out
Reset auto-scroll timer.

2024-11-11 01:25 UTC, boldenj2 commented on src/components/PhotoCarousal.js
> +    setTimeout(() => {
Reset auto-scroll timer.

2024-11-11 01:25 UTC, boldenj2 commented on src/components/PhotoCarousal.js
> +    setTimeout(() => {
Reset auto-scroll timer.

2024-11-11 22:34 UTC, alognz commented
lgtm but +1 the changes bolden said

2024-11-11 22:50 UTC, boldenj2 commented on src/components/PhotoCarousal.css
> +.carousel-container {
Make sure this file is in the `styles` folder.

2024-11-11 23:13 UTC, scuruchima1 commented
The new commits now include a timer that resets on every back, forth, and image button click. The component style file has now been moved to the proper folder as well. :)

2024-11-11 23:17 UTC, boldenj2 approved these changes
Looks good!

2024-11-11 23:17 UTC, merged