Adal/about page content
B-U-I-L-T-UIUC/BUILT-Website pull request #42
Opened 2024-11-12 00:02 UTC by Adrianv0512

## Preview
![image](https://github.com/user-attachments/assets/155b2b04-303e-41ce-b5df-f0bf568a7e67)
![image](https://github.com/user-attachments/assets/ca246c4f-1907-4c92-b84d-7a96317d5998)
![image](https://github.com/user-attachments/assets/e9001eb8-fdcd-4d82-9235-fb25aaad66f8)

## About Page Content
Added the content for the About Us page. This includes the structure of the page, all of the headings and text. Also added two new components which are used in the page: ValueCard and CardSlider. The value cards show the clubs values, and the card slider displays the eboard members. Only changed the about us, value card, and card slider css and js files. Also added all of the member photos into the public folder as well as the icons.

## Things to consider
- Add the rest of the members to the card slider
- Suggestions about the ordering of the section

2024-11-12 00:37 UTC, boldenj2 requested changes
Looks Good! Just need one minor change. On all of the e-board cards the text isa bit cluttered. Can we add some space between name, email, and bio?

Example:
![image](https://github.com/user-attachments/assets/f2757aa5-4a04-4086-9516-fd6010e11c87)

2024-11-12 06:00 UTC, scuruchima1 reviewed
Overall the code and design is good. I think some code formatting could help though and I have left comments for where it can improve.

2024-11-12 06:00 UTC, scuruchima1 commented on src/components/cardslider.js
> +const data = [
Let's parameterize the CardSlider component to take in data of this type, and put this data list in the about us page component. This will ensure we can reuse the component in the future if need be and will make it easier for others to see where the data is coming from.

2024-11-12 06:00 UTC, scuruchima1 commented on src/components/cardslider.js
> +        title: "Placeholder",
Not sure if this is on purpose or if this is something for the future, but updating placeholder to the appropriate title could be good.

2024-11-12 06:00 UTC, scuruchima1 commented on src/pages/aboutPage.js
> +                    <ValueCard url="graduation-cap-512.png" value="Academic Support" text="We provide resources and mentorship to help our members excel academically. From study groups to tutoring se
A couple things we can improve on here:
- Since ValueCard is a react component we don't need a closing tag, instead we just need something like `<ValueCard url="" value="" text=""/>` and that will work as well.
- We should separate the parameters in each ValueCard declaration, so that each of the parameters are on different lines. This will make it easier to read what each value card holds.
```javascript
<ValueCard 
    url="" 
    value="" 
    text=""
/>
```

2024-11-12 06:00 UTC, scuruchima1 commented on src/styles/aboutPage.css
> +}@import url('https://fonts.googleapis.com/css2?family=Merriweather:ital,wght@0,300;0,400;0,700;0,900;1,300;1,400;1,700;1,900&family=Titillium+Web:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,200;
Let's push these imports to the top of the file for consistency.

2024-11-19 01:39 UTC, boldenj2 approved these changes
lgtm, make sure to resolve comments when you have addressed them.

2024-11-20 23:42 UTC, scuruchima1 commented
@boldenj2 @Adrianv0512 @AdalPadilla Will review soon just have to study for an exam. 😀

2024-11-21 06:27 UTC, boldenj2 requested changes
One minor change. Please edit the order of the cards.

2024-11-21 06:27 UTC, boldenj2 commented on src/pages/aboutPage.js
> +        name: "Xochitl Zapata",
Put secretary before internal director and after treasurer.

2024-11-22 00:36 UTC, scuruchima1 approved these changes
Everything looks good to me! Left a comment that is more so a nit about formatting. +1 to Bolden's requested changes.

2024-11-22 00:36 UTC, scuruchima1 commented on src/pages/aboutPage.js
> +const data = [
I would put this data after the imports but before the AboutPage function declaration.

2024-12-02 04:13 UTC, boldenj2 approved these changes

2024-12-02 04:13 UTC, merged